<?php

function create_node_services_resources() {
  $index = array(
    'create_node' => array(// My new resource
      'create' => array(
        'callback' => 'create_node_perform',
        'access callback' => 'create_node_access',
        'args' => array(
          array(
            'name' => 'node',
            'optional' => FALSE,
            'source' => 'data', // Setting the source to 'data' in your args means that any data in the POST will be passed to the callback function
            'description' => 'The node data to create',
            'type' => 'array',
          ),
        ),
      ),
    ),
  );
  return $index;
}

function create_node_access() {
  return TRUE;
}

function create_node_perform($args) {
  $node = new stdClass();
  node_object_prepare($node);
  $node->type = 'page';
  $node->title =  $args['title'][''];
  $node->body['und'][0]['value'] = $args['body']['und'][0]['value'];
  $node->status=1;
  $filepath = 'http://localhost/site2/sites/default/files/a/after1.jpg';
  // Create managed File object and associate with Image field.
  $file = (object) array(
    'uid' => 1,
    'uri' => $filepath,
    'filemime' => file_get_mimetype($filepath),
    'status' => 1,
  );
  $filename='after1.jpg';
  $file = file_save_data(file_get_contents($filepath),'public://' . $filename, FILE_EXISTS_RENAME);

  $node->field_image1[LANGUAGE_NONE][0] = (array)$file;
  $node->field_tagline[LANGUAGE_NONE][0]['value'] ="ssss";
  $node->field_tagline[LANGUAGE_NONE][1]['value'] ="ttt";
  $node->field_tagline[LANGUAGE_NONE][2]['value'] ="uuuu";
  $node->language='und';
  $node->created=time();
  $node->uid="1";
  $node = node_submit($node);
  node_save($node);
}
